#ifndef __ObSYSTEM_H__
#define __ObSYSTEM_H__

// Generated by OberonViewer 0.7.5 on 2020-01-27T01:00:45
// Then further developed manually by RK

#include <OberonSystem/Ob_Global.h>

namespace Ob
{
	class SYSTEM : public _Root
	{
	public:
		static void GET(int _0, uint8_t _1);
        static int ADR(_ValArray<uint8_t> _0);
		static void PUT(int _0, char _1);
		static void LDREG(int _0, int _1);
        static int REG(int _0);
	};
}

#endif // __ObSYSTEM_H__
