#ifndef __ObDisplay_H__
#define __ObDisplay_H__

// Generated by OberonViewer 0.7.5 on 2020-01-27T01:00:45
// Then further developed manually by RK

#include <OberonSystem/Ob_Global.h>

namespace Ob
{
	class Display : public _Root
	{
	public:
		/* NW 5.11.2013 / 3.7.2016 / RK 25.1.20 */
		static Display* _inst();
		Display();
        void _init();
		~Display();

		// CONST
		/* black = background */
		static const int black = 0;
		static const int white = 1;
		/* modes */
		static const int replace = 0;
		static const int paint = 1;
		static const int invert = 2;

		// TYPE
		struct FrameMsg;
		struct FrameDesc;

		typedef FrameDesc* Frame;
		struct FrameMsg : public _Root {
		};
        typedef void (*Handler)(Frame F, FrameMsg& M );
		struct FrameDesc : public _Root {
			int H;
			int W;
			int X;
			int Y;
			Frame dsc;
			Handler handle;
			Frame next;
		};

		// VAR
		int Width;
		int Height;
        QByteArray arrow;
        QByteArray star;
        QByteArray hook;
        QByteArray updown;
        QByteArray block;

		// PROC
        static void ReplConst(int color, int x, int y, int w, int h, int mode);
        static void CopyPattern(int color, const QByteArray& pattern, int x, int y, int mode);
		static void CopyBlock(int sx, int sy, int w, int h, int dx, int dy, int mode);

	};
}

#endif // __ObDisplay_H__
