#ifndef __ObEdit_H__
#define __ObEdit_H__

// Generated by OberonViewer 0.7.5 on 2020-01-27T01:00:45
// Then further developed manually by RK

#include <OberonSystem/Ob_Global.h>
#include <OberonSystem/ObFiles.h>
#include <OberonSystem/ObFonts.h>
#include <OberonSystem/ObTexts.h>
#include <OberonSystem/ObDisplay.h>
#include <OberonSystem/ObViewers.h>
#include <OberonSystem/ObOberon.h>
#include <OberonSystem/ObMenuViewers.h>
#include <OberonSystem/ObTextFrames.h>

namespace Ob
{
	class Edit : public _Root
	{
	public:
		/* JG 2.11.90 / NW 28.11.2015 */
		static Edit* _inst();
		Edit();
        void _init();
		~Edit();

		// CONST
		static const char CR = 0x0D;
		static const int maxlen = 32;
        static const _ValArray<char> StandardMenu;

		// VAR
		Texts::Writer W;
		int time;
		int M;
		_FxArray<char,maxlen> pat;
		_FxArray<int,256> d;

		// PROC
		int Max(int i, int j);
		static void Open();
        static void Backup(_VarArray<char> name);
		static void Store();
		static void CopyLooks();
		static void ChangeFont();
		static void ChangeColor();
		static void ChangeOffset();
        static void Forward(int n, Texts::Reader& R, _VarArray<char> buf);
		static void Search();
		static void Locate();
		static void Recall();

	};
}

#endif // __ObEdit_H__
