#ifndef __ObFileDir_H__
#define __ObFileDir_H__

// Generated by OberonViewer 0.7.5 on 2020-01-27T01:00:45
// Then further developed manually by RK

#include <OberonSystem/Ob_Global.h>

namespace Ob
{
	class FileDir : public _Root
	{
	public:
		/* NW 12.1.86 / 23.8.90 / 15.8.2013 / RK 25.1.20 */
		static FileDir* _inst();
		FileDir();
		~FileDir();

		// CONST
		static const int FnLength = 32;
		static const int SectorSize = 1024;
		static const int HeaderSize = 352;

		// TYPE
		struct FileHeader;

		typedef int DiskAdr;
		typedef _FxArray<char,FnLength> FileName;
        typedef void (*EntryHandler)(_ValArray<char> /* FileName */ name, DiskAdr sec, bool& continue_);
		struct FileHeader : public _Root {
			int aleng;
			int bleng;
			int date;
		};

		// PROC
		static void Enumerate(_ValArray<char> prefix, EntryHandler proc);

	};
}

#endif // __ObFileDir_H__
