// Generated by OberonViewer 0.7.5 on 2020-01-27T01:00:45
// Then further developed manually by RK
#include "ObInput.h"
#include "QtDisplay.h"
#include <memory>
#include <QApplication>
using namespace Ob;

static owned_ptr<Input> s_inst;


Input* Input::_inst()
{
	if( s_inst.get() == 0 )
		s_inst.reset( new Input() );
	return s_inst.get();
}

int Input::Available()
{
    return 0; // Obsolete
}

void Input::Read(char& ch)
{
    // Obsolete
    ch = 0;
}

void Input::Mouse(_Set& keys, int& x, int& y)
{
    QtDisplay* d = QtDisplay::inst();
    d->d_lock++;
    QApplication::processEvents();
    x = d->d_xOb;
    y = d->d_yOb;
    keys = d->d_keys;
    d->d_lock--;
}

void Input::SetMouseLimits(int w, int h)
{
    // NOP
}

Input::Input()
{
}

Input::~Input()
{
    s_inst.release();
}

void Input::RegisterMouseHandler(Input::MouseHandler h)
{
    QtDisplay::registerMouseHandler(h);
}

void Input::RegisterCharHandler(Input::CharHandler h)
{
    QtDisplay::registerCharHandler(h);
}

void Input::RegisterIdleHandler(Input::IdleHandler h)
{
    QtDisplay::registerIdleHandler(h);
}

