#ifndef __ObKernel_H__
#define __ObKernel_H__

// Generated by OberonViewer 0.7.5 on 2020-01-27T01:00:45
// Then further developed manually by RK

#include <OberonSystem/Ob_Global.h>
#include <QDateTime>

namespace Ob
{
	class Kernel : public _Root
	{
	public:
		/* NW/PR  11.4.86 / 27.12.95 / 4.2.2014 / RK 25.1.20 */
		static Kernel* _inst();
		Kernel();
		~Kernel();

		// CONST
		static const int SectorLength = 1024;

		// TYPE
		typedef _FxArray<uint8_t,SectorLength> Sector;

		// VAR
		int allocated;
		int NofSectors;
		int heapOrg;
		int heapLim;
		int stackOrg;

		// PROC
		static void New(int& ptr, int tag);
		static void Mark(int pref);
		static void Scan();
        static void GetSector(int src, /*_VarArray<uint8_t> */ void* dst);
		int Time();
		int Clock();
        void SetClock(int dt);
		static void Install(int Padr, int at);

    private:
        int clock;
        QDateTime start;
	};
}

#endif // __ObKernel_H__
